# Generated by Django 4.1 on 2022-10-10 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_task_is_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 11, 2, 26, 13, 953136)
            ),
        ),
    ]
